// <auto-generated />
using System;
using MakeYourOwnPizza.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakeYourOwnPizza.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916103732_FixPizzaIdShadowProperty")]
    partial class FixPizzaIdShadowProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.CartIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CartItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("char(36)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartItemId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CartIngredient");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CartId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("PizzaId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("PizzaId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.EmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerification");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Ingredients", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("category")
                        .HasColumnType("int");

                    b.Property<string>("colorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("stock")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("apartment")
                        .HasColumnType("longtext");

                    b.Property<string>("city")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("district")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("driverId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("estimatedDelivery")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("floor")
                        .HasColumnType("longtext");

                    b.Property<string>("formattedAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("note")
                        .HasColumnType("longtext");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("street")
                        .HasColumnType("longtext");

                    b.Property<decimal>("totalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("userId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("driverId");

                    b.HasIndex("userId", "isActive");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IngredientsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ingredientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("orderItemId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientsId");

                    b.HasIndex("ingredientId");

                    b.HasIndex("orderItemId");

                    b.ToTable("OrderIngredient");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("orderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("pizzaId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("size")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("orderId");

                    b.HasIndex("pizzaId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("orderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("stageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("orderId", "createdAt", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("OrderStage");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("idempotentKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("orderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("paymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("transactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("orderId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Pizza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("refreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("refreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Cart", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("MakeYourOwnPizza.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.CartIngredient", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.CartItem", "CartItem")
                        .WithMany("Ingredients")
                        .HasForeignKey("CartItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Ingredients", "Ingredients")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CartItem");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Pizza", "Pizza")
                        .WithMany("CartItems")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cart");

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Driver", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.User", "User")
                        .WithOne("Driver")
                        .HasForeignKey("MakeYourOwnPizza.Domain.Entities.Driver", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.EmailVerification", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.User", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Order", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Driver", "driver")
                        .WithMany("Orders")
                        .HasForeignKey("driverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MakeYourOwnPizza.Domain.Entities.User", "user")
                        .WithMany("orders")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("driver");

                    b.Navigation("user");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderIngredient", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Ingredients", null)
                        .WithMany("orderIngredients")
                        .HasForeignKey("IngredientsId");

                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Ingredients", "Ingredient")
                        .WithMany()
                        .HasForeignKey("ingredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MakeYourOwnPizza.Domain.Entities.OrderItem", "orderItem")
                        .WithMany("orderIngredients")
                        .HasForeignKey("orderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("orderItem");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Order", "order")
                        .WithMany("orderItems")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Pizza", "pizza")
                        .WithMany("Orderitems")
                        .HasForeignKey("pizzaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("pizza");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderStage", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Order", "order")
                        .WithMany("orderStages")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MakeYourOwnPizza.Domain.Entities.Order", "order")
                        .WithMany("payments")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.CartItem", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Ingredients", b =>
                {
                    b.Navigation("orderIngredients");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Order", b =>
                {
                    b.Navigation("orderItems");

                    b.Navigation("orderStages");

                    b.Navigation("payments");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.OrderItem", b =>
                {
                    b.Navigation("orderIngredients");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.Pizza", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orderitems");
                });

            modelBuilder.Entity("MakeYourOwnPizza.Domain.Entities.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Driver")
                        .IsRequired();

                    b.Navigation("EmailVerifications");

                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
